# Generated by Django 3.0.4 on 2020-03-23 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('solutionManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrawingSolution',
            fields=[
                ('solution_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='solutionManager.Solution')),
                ('jsonObject', models.CharField(blank=True, default=None, max_length=100000)),
            ],
            bases=('solutionManager.solution', models.Model),
        ),
    ]
