# Generated by Django 3.0.4 on 2020-03-24 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drawingSolutions', '0002_auto_20200323_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drawingsolution',
            name='score',
        ),
    ]
