# Generated by Django 3.0.4 on 2020-03-24 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('setManager', '0002_auto_20200319_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemset',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
