# Generated by Django 3.0.4 on 2020-03-24 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_account_activation_code'),
        ('setManager', '0003_problemset_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemset',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounting.Account'),
        ),
    ]
