# Generated by Django 3.0.4 on 2020-03-19 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problemManager', '0002_auto_20200319_1849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='problem_set',
            new_name='problemSet',
        ),
    ]
