# Generated by Django 3.0.4 on 2020-03-19 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setManager', '0002_auto_20200319_1901'),
        ('problemManager', '0003_auto_20200319_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='problemSet',
        ),
        migrations.AddField(
            model_name='problem',
            name='problem_set',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='setManager.ProblemSet'),
        ),
    ]
