# Generated by Django 3.0.4 on 2020-03-19 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problemManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrawingProblem',
            fields=[
                ('problem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='problemManager.Problem')),
                ('goals_elements', models.CharField(blank=True, default='', max_length=1000)),
                ('costs', models.CharField(blank=True, default='', max_length=10000)),
            ],
            bases=('problemManager.problem', models.Model),
        ),
    ]
