# Generated by Django 3.0.4 on 2020-03-20 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawingProblems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawingproblem',
            name='costs',
            field=models.CharField(blank=True, default='[{"name": "POINT", "image_url": "https://wiki.geogebra.org/uploads/d/dc/Tool_New_Point.gif", "default_value": 0, "code": 1}, {"name": "JOIN", "image_url": "https://wiki.geogebra.org/uploads/d/d2/Tool_Line_through_Two_Points.gif", "default_value": 1, "code": 2}, {"name": "SEGMENT15", "image_url": "https://wiki.geogebra.org/uploads/c/cd/Tool_Segment_between_Two_Points.gif", "default_value": 1, "code": 15}, {"name": "CIRCLE_TWO_POINTS", "image_url": "https://wiki.geogebra.org/uploads/1/1e/Tool_Circle_Center_Point.gif", "default_value": 1, "code": 10}, {"name": "COMPASSES", "image_url": "https://wiki.geogebra.org/uploads/e/e3/Tool_Compasses.gif", "default_value": 1, "code": 53}, {"name": "CIRCLE_THREE_POINTS", "image_url": "https://wiki.geogebra.org/uploads/b/bc/Tool_Circle_3Points.gif", "default_value": 5, "code": 11}, {"name": "LINE_BISECTOR", "image_url": "https://wiki.geogebra.org/uploads/1/10/Tool_Perpendicular_Bisector.gif", "default_value": 3, "code": 8}, {"name": "ORTHOGONAL", "image_url": "https://wiki.geogebra.org/uploads/7/78/Tool_Perpendicular_Line.gif", "default_value": 4, "code": 4}, {"name": "MIDPOINT", "image_url": "https://wiki.geogebra.org/uploads/1/1c/Tool_Midpoint_or_Center.gif", "default_value": 3, "code": 19}, {"name": "PARALLEL", "image_url": "https://wiki.geogebra.org/uploads/f/fc/Tool_Parallel_Line.gif", "default_value": 4, "code": 3}, {"name": "ANGULAR_BISECTOR", "image_url": "https://wiki.geogebra.org/uploads/e/ed/Tool_Angular_Bisector.gif", "default_value": 3, "code": 9}]', max_length=10000),
        ),
        migrations.AlterField(
            model_name='drawingproblem',
            name='goals_elements',
            field=models.CharField(blank=True, default='[]', max_length=1000),
        ),
    ]
