# Generated by Django 3.0.4 on 2020-03-23 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0002_account_activation_code'),
        ('problemManager', '0004_auto_20200319_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Account')),
                ('problem', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='problemManager.Problem')),
            ],
        ),
    ]
