# Generated by Django 3.0.4 on 2020-03-24 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutionManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
