# Generated by Django 3.0.4 on 2020-03-16 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='activation_code',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
